[[input]]
filename = "/home/dkumar/data/shapiro/MCD/SimulatedData/Projections2/gamma45_CC_stack.tiff"
angles = "/home/dkumar/data/shapiro/MCD/SimulatedData/Projections2/angles.txt"
gamma = 45

[output]
filename = "jayden/recon45.tiff"
formats = ["tiff", "vti"] 

[recon_params]
max_iters = 40
tol = 1e-5
xtol = 1e-5
recon_dims = [21, 239, 239]

[regularizer]
method = "split_bregman"

[recon_params.regularizer.split_bregman]
lambda = 0.5
mu = 10
inner_iters = 1
