[[input]]
filename = "/home/dkumar/data/emma/665/Gamma0/aligned_XMCD_665_Gamma0.tiff"
angles = "/home/dkumar/data/emma/665/Gamma0/angles_shifted_665_Gamma0.txt"
gamma = 0

[output]
filename = "emma/665/tv/recon0.tiff"

[recon_params]
max_iters = 100
tol = 1e-5
xtol = 1e-5
recon_dims = [11, 511, 511]

[regularizer]
method = "split_bregman"

[recon_params.regularizer.split_bregman]
lambda = 0.5
mu = 10
inner_iters = 1


